### ISSUE TITLE
Mac OS X static CSS not updating

### ISSUE THREAD

**Issue by memphisvl** [LaraDock/laradock#128]
This issue relates to [SO question](http://stackoverflow.com/questions/29886153/css-refuses-to-update)

On Mac OS Docker 1.10.x when I updated public/css/app.css changes are not reflected in browser, this is due to sendfile issue in VirtualBox.

To fix this in laradock nginx conf must be updated:
```
user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
  worker_connections  2048;
  multi_accept on;
  use epoll;
}

http {
  server_tokens off;
  sendfile off; # must be off
  tcp_nopush off; # must be off
  tcp_nodelay off; # must be off
  keepalive_timeout 15;
  types_hash_max_size 2048;
  client_max_body_size 20M;
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log on;
  error_log on;
  gzip on;
  gzip_disable "msie6";
  include /etc/nginx/conf.d/*.conf;
  include /etc/nginx/sites-available/*;
  #open_file_cache max=100;
}
daemon off;
```

**Comment by jon-heller** [comment]
Thanks so much, I was pulling my hair out because of this

**Comment by Mahmoudz** [comment]
So I think this Issue is solved! :)

**Comment by ZeroZipZilch** [comment]
Hm, sorry if I'm wrong and for commenting on a closed issue, but I think this is still an issue. Or like, I encountered this problem, and Googled, and found this, and applied the fixes mentioned, and ran docker-compose build nginx, and after that it started working. Is there any reason why the above config isn't the default one?
