### ISSUE TITLE
404 Not Found 7.1.16-1

### ISSUE THREAD

**Issue by rjcfj** [laradock/laradock#1534]
### Info:
- Docker version (`$ docker --version`): Docker version 18.03.1-ce, build 9ee9f40
- Laradock commit (`$ git rev-parse HEAD`): 0c41fceae1b23089f5360dc4f8aeb85719c7bf5a
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10 PRO

### Issue:
Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php7.1-ldap amd64 7.1.16-1+ubuntu16.04.1+deb.sury.org+1
  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.1/php7.1-ldap_7.1.16-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_LDAP} = true ]; then     apt-get install -y libldap2-dev &&     apt-get install -y php${PHP_VERSION}-ldap ;fi' returned a non-zero code: 100
_____

### Reproduce:
Not Found
The requested URL /ondrej/php/ubuntu/pool/main/p/php7.1/php7.1-ldap_7.1.16-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb was not found on this server.

**Comment by cyberbit** [comment]
I'm having the same problem with INSTALL_SOAP:

```
Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php7.2-soap amd64 7.2.4-1+ubuntu16.04.1+deb.sury.org+1
  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.2/php7.2-soap_7.2.4-1+ubuntu16.04.1+deb.sury.org+1_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_SOAP} = true ]; then   apt-get -y install libxml2-dev php${PHP_VERSION}-soap ;fi' returned a non-zero code: 100
```

**Comment by mariwing** [comment]
The site where the package is updated from don't have version 7.2.4 anymore, only 7.2.5. I am a docker (and Linux) newbie; anyone care to share where this url is coming from? Is it something I could update somewhere in the docker files I have locally?

**Comment by cyberbit** [comment]
@mariwing Unfortunately the only solution for me was to downgrade my entire Laradock instance. I tried to do it in place but that took many hours of slowly tweaking configuration files and rebuilding containers before it worked. Honestly it's probably quicker to re-clone the repository from a previous point in history, clear the data cache, and add back the sites. The commit that I reverted to is 188a7d7.

**Comment by philipptempel** [comment]
What appears to be happening here is that there are a few `apt-get install` commands for several packages where the local package repo is out of sync with the remote. In an interactive environment, this would be seen by the user and an appropriate `apt-get update` would be run. However, the Dockerfile does not contain any package repo update commands, as such the current layer has a different package repo list than the remote. This is in general the "problem" with dockers layers as they will be re-used if their command didn't change (something I, too, had to learn the hard way).

What seems to be resolving the issue is to call `apt-get update -yqq` before any `apt-get install` within the `Dockerfiles` in question (I did this in `workspace/Dockerfile` and `php-fpm/Dockerfile` for the sake of testing with PHP 7.1).

However, I cannot confirm these are the only places changes need to be made, but it's a start (that's why I'm not creating a PR).

**Comment by napogf** [comment]
Great! modifyng workspace/Dockerfile and running apt-get update -yqq container will build without problems.

**Comment by hounded** [comment]
pull request anyone?

**Comment by bestlong** [comment]
I think this issue is fixed by #1569 .

**Comment by Dannymx** [comment]
This still seems to be an issue, even though my Dockerfile have the apt-get update (both workspace and php-fpm) `apt-get update -yqq` I still get this error:

```
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Service 'workspace' failed to build: The command '/bin/sh -c if [ ${INSTALL_SOAP} = true ]; then   apt-get -y install libxml2-dev php${LARADOCK_PHP_VERSION}-soap ;fi' returned a non-zero code: 100
```

Restarting Docker didn't fix my issue either.
