### ISSUE TITLE
Nginx not running with State Exit 2

### ISSUE THREAD

**Issue by dendihandian** [laradock/laradock#1878]
### Info:
- Docker version (`$ docker --version`): 18.06.1-ce
- Laradock commit (`$ git rev-parse HEAD`): 0ed5487ed7204aff6897db8de14e1e79469280fd
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10

### Issue:
Cannot Start Nginx After First Build and Restart
`docker-compose ps`:
```
The system cannot find the path specified.
           Name                          Command              State                  Ports
--------------------------------------------------------------------------------------------------------
laradock_docker-in-docker_1   dockerd-entrypoint.sh           Up       2375/tcp
laradock_mysql_1              docker-entrypoint.sh mysqld     Up       0.0.0.0:3306->3306/tcp, 33060/tcp
laradock_nginx_1              /bin/bash /opt/startup.sh       Exit 2
laradock_php-fpm_1            docker-php-entrypoint php-fpm   Up       9000/tcp
laradock_workspace_1          /sbin/my_init                   Up       0.0.0.0:2222->22/tcp
```
_____

### Expected behavior:
Nginx Running Successfuly
_____

### Reproduce:
Just followed official documentation, error occured (only nginx) when I start with `docker compose -d nginx mysql`
_____

### Relevant Code:

```
`docker-compose logs nginx`:
```

```
Attaching to laradock_nginx_1
nginx_1                | /opt/startup.sh: line 2: $'\r': command not found
nginx_1                | /opt/startup.sh: line 10: syntax error: unexpected end of file
nginx_1                | /opt/startup.sh: line 2: $'\r': command not found
nginx_1                | /opt/startup.sh: line 10: syntax error: unexpected end of file
```

**Comment by ludo237** [comment]
Right now the only workaround is to "disable" the `startup.sh` script and change the CMD command inside nginx Dockerfile

**Comment by Shchepotin** [comment]
Sorry for this, I'll fix it as soon as possible.

**Comment by ludo237** [comment]
@Shchepotin shit happens dont' worry

**Comment by matthijs-neijenhuijs** [comment]
i have the same problem that nginx is not working at windows 10. Is there already a solution?

**Comment by Shchepotin** [comment]
Yes, but not yet merged  #1879

**Comment by ludo237** [comment]
@matthijs-neijenhuijs My current work around is the only solution until the merge is accepted

**Comment by iamzhuyi** [comment]
@ludo237 i have bring backed <a href="https://github.com/laradock/laradock/pull/1527/files#diff-296e14ae0dc392c7edd9369908467953L27">this line</a> but still doesn't work

**Comment by Shchepotin** [comment]
@ludo237 @matthijs-neijenhuijs @iamzhuyi for fix this issue add [this line](https://github.com/laradock/laradock/pull/1879/files#diff-296e14ae0dc392c7edd9369908467953R29)

**Comment by iamzhuyi** [comment]
@Shchepotin @ludo237 thanks，it's my first time use docker, and i don't know the image should rebuild when the dockerfile change 🤣

**Comment by junichimura** [comment]
I had the same problem.
I think that it is a problem that meta characters are included in / nginx / startup.sh.
Laradock works without problems by changing / nginx / startup.sh in my environment.

**Comment by ludo237** [comment]
@junichimura it has been fixed already but the [PR is still open somehow](https://github.com/laradock/laradock/pull/1879)

**Comment by tim2fx** [comment]
guys I've added this and rebuild the image but still doesn't work 😳@ludo237 @iamzhuyi

**Comment by JHChan314** [comment]
> @ludo237 @matthijs-neijenhuijs @iamzhuyi for fix this issue add [this line](https://github.com/laradock/laradock/pull/1879/files#diff-296e14ae0dc392c7edd9369908467953R29)

Add that line still don't work.
After add `RUN sed -i 's/\r//g' /opt/startup.sh` , then I run `docker-compose down` `docker-compose up -d nginx mysql redis workspace`, still samp problems `docker-compose logs nginx` :
```
Attaching to laradock_nginx_1_204e51496d22
nginx_1_204e51496d22   | /opt/startup.sh: line 2: $'\r': command not found
nginx_1_204e51496d22   | /opt/startup.sh: line 10: syntax error: unexpected end of file
```

Docker version 18.09.0, build 4d60db4
docker-compose version 1.23.1, build b02f1306

**Comment by ludo237** [comment]
You need to rebuild from scratch ...

**Comment by ludo237** [comment]
# How to fix this problem

There is literally a PR that fix this problem....
