### ISSUE TITLE
Cannot connect to MySQL from Workspace and phpmyadmin

### ISSUE THREAD

**Issue by callect** [LaraDock/laradock#348]
My nginx worked well (localhost), but I'm unable to connect to the MySQL container from the Workspace one with php artisan migrate

> [PDOException]
  SQLSTATE[HY000] [2002] No such file or directory

`environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root`
and I enter phpmyadmin in browser (localhost:8080) ,I got the same error

No such file or directory

What can i do?

**Comment by philtrep** [comment]
@callect

Could you make sure the MySQL container is `up` ? If it is, please try to connect to the database directly from it 
```
docker-compose exec mysql bash

mysql homestead -u homestead -psecret
```

Let me know

**Comment by manshoor** [comment]
I'm having the same issue.
http://screencast.com/t/rfhfDrL5D8

**Comment by manshoor** [comment]
#344 
I believe this is the issue, you have to add the ports in order to make it work.

**Comment by callect** [comment]
@philtrep yes , l can connect to database directly from MySQL container

**Comment by Mahmoudz** [comment]
Hi all, please pull the latest version of LaraDock (currently it's v4.7.3) and try again. This problem should be solved.

**Comment by callect** [comment]
@Mahmoudz ok,it's solved,thank you.

**Comment by imamassi** [comment]
Hello,

I don't know why but this error still happened to me, I got SQLSTATE[HY000] [2002] Connection refused even though I'm pretty sure I got everything right. The ports already set, database information is correct, the only thing I change from current release is NGINX port and the laravel code volume. I'm not sure what am I doing wrong.

Thanks.

**Comment by imamassi** [comment]
```
in Connector.php line 119
at PDO->__construct('mysql:host=127.0.0.1;port=3306;dbname=homestead', 'homestead', 'secret', array('0', '2', '0', false, false)) in Connector.php line 119
at Connector->createPdoConnection('mysql:host=127.0.0.1;port=3306;dbname=homestead', 'homestead', 'secret', array('0', '2', '0', false, false)) in Connector.php line 56
at Connector->createConnection('mysql:host=127.0.0.1;port=3306;dbname=homestead', array('driver' => 'mysql', 'host' => '127.0.0.1', 'port' => '3306', 'database' => 'homestead', 'username' => 'homestead', 'password' => 'secret', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => '', 'strict' => true, 'engine' => null, 'name' => 'mysql'), array('0', '2', '0', false, false)) in MySqlConnector.php line 24
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => '127.0.0.1', 'port' => '3306', 'database' => 'homestead', 'username' => 'homestead', 'password' => 'secret', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => '', 'strict' => true, 'engine' => null, 'name' => 'mysql')) in ConnectionFactory.php line 100
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure)) in Connection.php line 956
at Connection->getPdo() in Connection.php line 824
at Connection->reconnectIfMissingConnection() in Connection.php line 709
at Connection->run('select * from `users`', array(), object(Closure)) in Connection.php line 351
at Connection->select('select * from `users`', array(), true) in Builder.php line 1648
at Builder->runSelect() in Builder.php line 1634
at Builder->get(array('*')) in Builder.php line 613
at Builder->getModels(array('*')) in Builder.php line 318
at Builder->get(array('*')) in Model.php line 632
at Model::all() in web.php line 15
at RouteServiceProvider->{closure}() in Route.php line 176
at Route->runCallable() in Route.php line 147
at Route->run(object(Request)) in Router.php line 642
at Router->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
at Pipeline->then(object(Closure)) in Router.php line 644
at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 618
at Router->dispatchToRoute(object(Request)) in Router.php line 596
at Router->dispatch(object(Request)) in Kernel.php line 267
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
at Pipeline->then(object(Closure)) in Kernel.php line 149
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 116
at Kernel->handle(object(Request)) in index.php line 53

```

The exception

**Comment by imamassi** [comment]
I resolved the issue by changing the 'DB_HOST' in laravel .env to the current running container IP that I got from dumping `Request::ip()` on my application.
